name: Authenticate

on:
  push:
    branches:
    - main
    - 'branch-*'
  pull_request:
    branches:
    - main
    - 'branch-*'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  # PasswordAuthenticator
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla-passauth
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --username cassandra --password cassandra --debug" --health-interval 5s --health-retries 30
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --verbose authenticate_superuser -- custom_authentication --ignored
