# This workflow builds the book with documentation and runs book tests
name: Book

on:
  push:
    branches:
    - main
    - 'branch-*'
  pull_request:
    branches:
    - main
    - 'branch-*'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug scylladb" --health-interval 5s --health-retries 10
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: Install mdbook
      uses: taiki-e/install-action@v2
      with:
        tool: mdbook
    - name: Build the project
      run: cargo build --verbose --examples
    - name: Build the book
      run: mdbook build docs
    - name: Build the book using the script
      run: python3 docs/build_book.py
    - name: Run book tests
      run: mdbook test -L target/debug/deps docs
